steps:
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting the build process..."
        python hello.py
        echo "Build process completed successfully!"
options:
  logging: CLOUD_LOGGING_ONLY
  #logging: None
# logsBucket: 'gs://gcp-devops-bucket-2'