substitutions:
  _ENV: 'production'  
  _SERVICE_NAME: 'my-service'
  _REGION: 'us-central1'

steps:
  - name : 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "===Built-in Variable==="
        echo "Project ID: $PROJECT_ID"
        echo "Repository Name: $REPO_NAME"
        echo "Branch Name: $BRANCH_NAME"
        echo "Trigger Name: $TRIGGER_NAME"
        echo "Commit SHA: $COMMIT_SHA"
  - name : 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "===Custom-in Variable===" >> output/info.txt
        echo "Environment: $_ENV"?? >> output/info.txt  
        echo "Service Name: $_SERVICE_NAME" >> output/info.txt
        echo "Region: $_REGION" >> output/info.txt      
artifacts:
  objects:
    location: 'gs://gcp-devops-bucket-2/artifacts/'
    paths: ['output/**']        

options:
  logging: CLOUD_LOGGING_ONLY        